subdir-ccflags-$(CONFIG_PPC_WERROR) := 

obj-y				+= xics-common.o
obj-$(CONFIG_PPC_ICP_NATIVE)	+= icp-native.o
obj-$(CONFIG_PPC_ICP_HV)	+= icp-hv.o
obj-$(CONFIG_PPC_ICS_RTAS)	+= ics-rtas.o
obj-$(CONFIG_PPC_POWERNV)	+= ics-opal.o icp-opal.o
